name: Build

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  DISCORD_WEBHOOK_TASK_STATUS: ${{ secrets.DISCORD_WEBHOOK_URL }}

# Controls when the action will run. 
on:
  workflow_dispatch: { }
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2021.3.4f1
        targetPlatform:
          - StandaloneWindows64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          clean: false
      
      #Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library
      
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2.0.3
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      
      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r .github/send_download_artifact_url/requirements.txt
      - name: send download artifact page url
        run: |
          python .github/send_download_artifact_url/send-download-artifact-page-url.py